if(NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT is required")
endif()
if(NOT DEFINED OUTPUT_C)
    message(FATAL_ERROR "OUTPUT_C is required")
endif()
if(NOT DEFINED OUTPUT_H)
    message(FATAL_ERROR "OUTPUT_H is required")
endif()
if(NOT DEFINED SYMBOL)
    message(FATAL_ERROR "SYMBOL is required")
endif()

file(READ "${INPUT}" WASM_HEX HEX)
string(LENGTH "${WASM_HEX}" WASM_HEX_LEN)
math(EXPR WASM_SIZE "${WASM_HEX_LEN} / 2")

set(WASM_BYTES "")
set(WASM_LINE "  ")
math(EXPR WASM_LAST_INDEX "${WASM_SIZE} - 1")
foreach(I RANGE 0 ${WASM_LAST_INDEX})
    math(EXPR HEX_OFFSET "${I} * 2")
    string(SUBSTRING "${WASM_HEX}" ${HEX_OFFSET} 2 BYTE_HEX)
    string(APPEND WASM_LINE "0x${BYTE_HEX}")
    if(NOT I EQUAL WASM_LAST_INDEX)
        string(APPEND WASM_LINE ", ")
    endif()
    math(EXPR LINE_COUNT "(${I} + 1) % 12")
    if(LINE_COUNT EQUAL 0)
        string(APPEND WASM_BYTES "${WASM_LINE}\n")
        set(WASM_LINE "  ")
    endif()
endforeach()
if(NOT WASM_LINE STREQUAL "  ")
    string(APPEND WASM_BYTES "${WASM_LINE}\n")
endif()

file(WRITE "${OUTPUT_H}" "#ifndef EMBEDDED_WASM_H\n")
file(APPEND "${OUTPUT_H}" "#define EMBEDDED_WASM_H\n\n")
file(APPEND "${OUTPUT_H}" "#include <stddef.h>\n")
file(APPEND "${OUTPUT_H}" "#include <stdint.h>\n\n")
file(APPEND "${OUTPUT_H}" "extern const uint8_t ${SYMBOL}[];\n")
file(APPEND "${OUTPUT_H}" "extern const size_t ${SYMBOL}_size;\n\n")
file(APPEND "${OUTPUT_H}" "#endif /* EMBEDDED_WASM_H */\n")

file(WRITE "${OUTPUT_C}" "#include \"embedded_wasm.h\"\n\n")
file(APPEND "${OUTPUT_C}" "const uint8_t ${SYMBOL}[] = {\n")
file(APPEND "${OUTPUT_C}" "${WASM_BYTES}")
file(APPEND "${OUTPUT_C}" "};\n\n")
file(APPEND "${OUTPUT_C}" "const size_t ${SYMBOL}_size = sizeof(${SYMBOL});\n")
